### ISSUE TITLE
Plasma 6

### ISSUE THREAD

**Issue by bglebrun** [subpop/wallhaven-wallpaper-plasma#9]
Any plans currently to port this for Plasma 6?

**Comment by bglebrun** [comment]
I'm taking a look at it myself

**Comment by Mohit-Pala** [comment]
came here to request plasma 6, i used this plugin a lot on plasma 5

**Comment by idkwhatido** [comment]
> I'm taking a look at it myself

Hi, did you had the time to look in it already?

**Comment by bglebrun** [comment]
Life has been busy but I should have time to look at this in the next week.

**Comment by TheSoultrigger** [comment]
If you can get it working for KDE Plasma 6 I will highly appreciate it

**Comment by Blacksuan19** [comment]
I have made a fully working plasma 6 port with some additional features.
you can install it from get new plugins or from source here
https://github.com/Blacksuan19/plasma-wallpaper-wallhaven-reborn

**Comment by subpop** [comment]
Thanks for the port @Blacksuan19! Life got away from me and I never got back to this. I'll link to your Plasma 6 variant from my README in case people come looking.
